version: '3'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/var/www/html
      # Mount config for development
      - ./docker/nginx:/etc/nginx/conf.d:cached
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db
    networks:
      - laravel

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: blog-php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html:cached
    links:
      - db
    depends_on:
      - db
    networks:
      - laravel

  db:
    build: docker/psql
    ports:
      - 11:5432
    container_name: blog-db
    restart: unless-stopped
    volumes:
      - ./docker/psql/db-cache:/var/lib/postgresql
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=dev_blog
      - POSTGRES_PASSWORD=blog
    networks:
      - laravel


  node:
    image: node:14.1.0-alpine3.11
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
    tty: true
    working_dir: /var/www/html/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.111.0/28
